---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  api/v1/tasks:
    post:
      summary: creates a task
      tags:
      - Tasks
      parameters: []
      responses:
        '201':
          description: task created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
              required:
              - title
              - description
          application/xml:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
              required:
              - title
              - description
  "/api/v1/tasks/{id}":
    get:
      summary: Retrieves a task
      tags:
      - Tasks
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: task found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
                required:
                - id
                - name
                - status
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
                required:
                - id
                - name
                - status
        '404':
          description: task not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
